theme: jekyll-theme-dinky
title: "Lisa's Writings and stuff"
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
relative_links:
  enabled: true
  collections: true
include:
  - '**/**.md'
